let a = [4,5,6];
a[0]; // => 4 (array access by index - zero based)
a[2]; // => 6 (array access)

let b = ["cat", "dog", "fish"];

let c = ["cat", 100, true, 'hi'];

c.push('hi'); // adds items to the end of an array

// looping over an array to get each value
for (let i = 0; i < c.length; i++) {
	console.log(c[i]);
}
